In [29]:
n=7; 
p=1;
s=1; 
l=3;
k=n+(2*p)
import numpy as np
import math
A = np.random.randint(10,size=(n,n,l))
p_m = np.zeros([k,k,l],dtype=int)
f = np.array([[1,0,-1],[1,0,-1],[1,0,-1]]);
for v in range(0,l):
    for i in range (0,n):
        for a in range(0,n):
             p_m[i+p,a+p,v] = A[i,a,v]
  
r1=len(p_m);
fs=len(f);
A1=[];
B=[]
cc=np.zeros([(math.floor((n+(2*p)-fs)/s +1)),(math.floor((n+(2*p)-fs)/s +1)),l],dtype=int)
strr = range(0,r1-fs+1,s)
for v in range(0,l):
    for r in strr:    
        for c in strr:
              A1=np.multiply(p_m[r:r+fs,c:c+fs,v],f)
              B.append(np.sum(A1))
 
kk=np.reshape(B,(math.floor((n+(2*p)-fs)/s +1),math.floor((n+(2*p)-fs)/s +1),l))
cc = np.multiply(kk,(-1))
tt=np.zeros([(math.floor((n+(2*p)-fs)/s +1)),(math.floor((n+(2*p)-fs)/s +1))])
for r in range(0,l):
    tt=cc[:,:,r]+tt

print("Final Matrix:")
print(tt)

Final Matrix:
[[ 17. -11.  22. -14.   3.   9. -34.]
 [ 11.  -7.  -8.   0.  13.  -9. -15.]
 [  1.   1.   5.  -4.   2.  -2. -24.]
 [ 13. -15.   4.   0.   5.   6. -15.]
 [  8.   0.  11. -21.   1.  10.  -1.]
 [ 12.  11.  -8.   9.   7. -13.  -5.]
 [ -3.  11. -14.   9. -15.   2. -14.]]
